openapi: 3.0.0
info:
  title: Weather-App_v2
  version: 1.0.0
servers:
  - url: http://{{local}}
  - url: http://localhost:3000/api/v1
paths:
  /getAddressCoordinates:
    get:
      tags:
        - default
      summary: get coordinates
      parameters:
        - name: address
          in: query
          schema:
            type: string
          example: Red Fort
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /getForeCast:
    get:
      tags:
        - default
      summary: get forecast
      parameters:
        - name: lat
          in: query
          schema:
            type: integer
          example: '0'
        - name: long
          in: query
          schema:
            type: integer
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /getAddressForeCast:
    get:
      tags:
        - default
      summary: get address forecast
      parameters:
        - name: address
          in: query
          schema:
            type: string
          example: mumbai
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
